bool isAlive();
int getEnergy();
int getHungry();
int getClean();
int getMaxEnergy();
int getMaxHungry();
int getMaxClean();
int getDiamonds();
int getAge();
void setAlive(bool status);
void setEnergy(int energy);
void setHungry(int hungry);
void setClean(int clean);
void setMaxEnergy(int max_energy);
void setMaxHungry(int max_hungry);
void setMaxClean(int max_clean);
void setDiamonds(int diamonds);
void setAge(int age);
Pet(int max_energy=0, int max_hungry=0, int max_clean=0);
bool sleep();
bool eat();
bool play();
bool analyse();
bool cleaner();
string toString();